# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5724534ee20a7d91ac0af758ed6460e3cf43be33897d0a8102c75296dd8c49c16f3bafe7a97e279301b967657f1ecde720f60e526ca2cf203b958ae5f89bb766

test:
  secret_key_base: a4898831e095fb573b4f792cda57f7763a154e36732164906440204067c204af2cd8a67683722bba0a37327a98e87b6d797d3a4508f7bd823179600e2f17f6fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
